### PR TITLE
simpler code and cleanup

### PR DESCRIPTION
**Pull request by harlanx**
same function as what the PR's goal is but with simpler code. Also mob drop radius max's is increased to what mob vacuum radius can offer.

### CODE REVIEW

**Comment by harlanx** [comment]
@biswop I remembered in your initial PR that you were asking for some code cleanup. Can you have a look on the changes made. Just want to make sure this is still the same goal on your PR in the main repo.

**Comment by biswop** [comment]
it's not working the way it was, its pulling all the things with it even when i set the normal radius to 5 it pulls everything so it just acts like another normal radius setting

**Comment by harlanx** [comment]
> it's not working the way it was, its pulling all the things with it even when i set the normal radius to 5 it pulls everything so it just acts like another normal radius setting

I see. I'll look into what seems to be causing the problem because the logic seems fine to me already.

**Comment by harlanx** [comment]
found the bug lol. can you try it again?
Here's a preview where (sunsettia) non mob drops with short radius are not getting pulled.
image

**Pull request merged**
